version: '3.8'

services:
  app:
    build: .
    image: yourdockerhubusername/go-http-db:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app_db?sslmode=disable
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: postgres:15
    restart: "on-failure"
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "while ! pg_isready -h db -U postgres; do sleep 1; done &&
             psql -h db -U postgres -d app_db -f /migrations/001_init.sql"

volumes:
  db_data:
